var sponsorArray=new Array();var no_sponsor_list_link=0;sponsorArray.push(new Array("logo1_224_1416199311.html","",""));sponsorArray.push(new Array("logo1_1086_1396508111.html","",""));sponsorArray.push(new Array("logo1_11_1302607095.html","",""));sponsorArray.push(new Array("logo1_1361_1415337769.html","",""));sponsorArray.push(new Array("logo1_1116_1398321631.html","",""));sponsorArray.push(new Array("logo1_1179_1400571582.html","",""));sponsorArray.push(new Array("logo1_1153_1399876584.html","",""));sponsorArray.push(new Array("logo1_60_1302609187.html","pokies-net.com/policy/privacy",""));sponsorArray.push(new Array("logo1_83_1302608199.html","",""));sponsorArray.push(new Array("logo1_1273_1408083735.html","",""));var ST_speed=8000;var zeiger=Math.floor(Math.random()*sponsorArray.length);var label=1;var labeltext='Partners';var sponsorlimit='1';if(sponsorArray.length<sponsorlimit){sponsorlimit=sponsorArray.length;}
var do_preload=true;var first_pointer=zeiger;function testLogo(z){if(z>=sponsorArray.length||sponsorArray[z][2]!=""&&sponsorArray[z][2]!=sponsor_switch){return false;}
return true;}
function preload_some_images(tmp_zeiger){var start=tmp_zeiger-1;if(start<0)start=sponsorArray.length-1;for(var k=0;k<sponsorlimit;k++){while(!testLogo(tmp_zeiger)){if(tmp_zeiger==start){continue;}
tmp_zeiger++;if(tmp_zeiger>sponsorArray.length-1)tmp_zeiger=0;}
preload_some=new Image();preload_some.src="../files/web/sponsor/_logos/"+sponsorArray[tmp_zeiger][0];if(tmp_zeiger==start)k=sponsorlimit;tmp_zeiger++;if(tmp_zeiger>sponsorArray.length-1)tmp_zeiger=0;}}
if(do_preload&&sponsorArray.length!=0)preload_some_images(zeiger);function sponsorenSlide(){if(sponsorArray.length==0)return false;var ausgabe='<div id="sponsorlocker">';if(label)ausgabe+='<span id="sponsortitlebin" class="sponsorbin"><span id="sponsortitle">'+labeltext+'</span></span>';var start=zeiger-1;if(start<0)start=sponsorArray.length-1;for(var k=0;k<sponsorlimit;k++){while(!testLogo(zeiger)){if(zeiger==start){continue;}
zeiger++;if(zeiger>sponsorArray.length-1)zeiger=0;}
ausgabe+='<span id="sp'+(k+1)+'" class="sponsorbin">';if(sponsorArray[zeiger][1]!=""&&!no_sponsor_list_link)ausgabe+='<a class="sponsorclick" href="http://'+sponsorArray[zeiger][1]+'" target="_blank">';ausgabe+='<img class="sponsorimg" src="../files/web/sponsor/_logos/'+sponsorArray[zeiger][0]+'" alt="" title="" />';if(sponsorArray[zeiger][1]!=""&&!no_sponsor_list_link)ausgabe+='</a>';ausgabe+='</span>';if(zeiger==start)k=sponsorlimit;zeiger++;if(zeiger>sponsorArray.length-1)zeiger=0;if(zeiger==first_pointer)do_preload=false;}
ausgabe+='<span class="cleaner">&nbsp;</span></div>';var printAusgabe=true;if(printAusgabe){if(document.getElementById("sponsoren_spacer")){document.getElementById("sponsoren_spacer").innerHTML=ausgabe;}else{if(document.getElementById("sponsorenSpacer")){document.getElementById("sponsorenSpacer").innerHTML=ausgabe;}else{if(document.getElementById("sponsors")){document.getElementById("sponsors").innerHTML=ausgabe;}}}}
if(do_preload&&sponsorArray.length!=0)preload_some_images(zeiger);setTimeout("sponsorenSlide()",ST_speed);}